##**Name**         
**Izaz Khan**
##**Reg no**
**B23F0001AI029**

##**Scenario 1: Student Marks Analysis (NumPy)**

##**Descreption**
In the first task i learn about numpy , how to instal it, then how we can do computation on array.

1->I find the mean

2->I found out numbers above average

3->I reshape it

**Importing the Librarey**

In [ ]:
import numpy as np

**Finding the mean using np.mean() function**

In [ ]:

marks=np.array([45,67,89,32,76,50,89,44,61,39])
print(marks)
print(np.mean(marks))
print(np.median(marks))


[45 67 89 32 76 50 89 44 61 39]
59.2
55.5


**Printing those numbers which are above mean**

In [ ]:
print(np.mean(marks))
above_average=marks[marks>np.mean(marks)]
print(above_average)

59.2
[67 89 76 89 61]


**Reshaping our array from 1 row to 2 rows**

In [ ]:
print("original one dimensional array:",marks)
reshape=marks.reshape(2,5)
print("the two dimensional array:", reshape)

original one dimensional array: [45 67 89 32 76 50 89 44 61 39]
the two dimensional array: [[45 67 89 32 76]
 [50 89 44 61 39]]


##**Scenario 2: Fruit Shop Inventory (Pandas Series)**

#**Description**
The second task is about Pandas library and how we can do data manipulation using pandas

- First i import pandas to my working notebook
- second i print all the data
- third i print the specific which is out of stock
- Fourth i update the stock by adding new delivery of some stock
- last i print the total stock available

**Importing pandas library and print out the series**

In [3]:
import pandas as pd

In [ ]:
stock=pd.Series([20,15,0,8],index=['apple','banana','cheeries','Date'])
print(stock)

apple       20
banana      15
cheeries     0
Date         8
dtype: int64


**Print out those stocks which are not available**

In [ ]:
out_of_stock=stock[stock==0]
print(out_of_stock)

cheeries    0
dtype: int64


**Update the inventory by adding new delivery**

In [ ]:
update=pd.Series([10,5,20], index=['apple','banana','Date'])
print(update)

apple     10
banana     5
Date      20
dtype: int64


**Print out the updated Inventory**

In [ ]:
stock.add(update)

Date        28.0
apple       30.0
banana      20.0
cheeries     NaN
dtype: float64

In [ ]:
stock.add(update,fill_value=0)

Date        28.0
apple       30.0
banana      20.0
cheeries     0.0
dtype: float64

#**Task 3: Mini Student Records (Pandas DataFrame)**

#**Description**
In second task i worked on series now in third its about pandas framework
- First i print out all the data
- Second i print the student with hieghest score
- Third i find the Avreage
- Last i compare the student with average and print those who lies above average

**Panda Data Frame and print it out**

In [4]:
data={ 'Name':['Izaz','Shuhood','Ibad', 'Salif', 'Hammad'],
       'Age':[20,25,19,21,22],
       'Score':[68,70,78,85,88]
       }
df=pd.DataFrame(data)
print(df)



      Name  Age  Score
0     Izaz   20     68
1  Shuhood   25     70
2     Ibad   19     78
3    Salif   21     85
4   Hammad   22     88


**Finding the individual with hieghest score**

In [8]:
highest = df[df['Score'] == df['Score'].max()]
print(highest)

     Name  Age  Score
4  Hammad   22     88


**Finding the mean**

In [9]:
avrage=df['Score'].mean()
print(avrage)

77.8


**Printing those who lies above average**

In [10]:
above_average=df['Score'] > avrage
print(above_average)

0    False
1    False
2     True
3     True
4     True
Name: Score, dtype: bool


#**Conclusion**
This our first Lab of **ML** , we studied about the 2 fundamental libraries **NumPy & Panda**. One is used for Methemathical computation second one is for data Manifulation.Last we have 3 task about these two libraries which enhanced our programming skills and fimiliar us with these libraries how to used it .